language: node_js

node_js: --lts

env: EFF_NO_LINK_RULES=true PARSER_NO_WATCH=true

cache:
  - yarn
  - directories:
      - .changelog

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - git config --global user.name "JounQin"
  - git config --global user.email "admin@1stg.me"

install:
  - yarn --frozen-lockfile
  - yarn lerna bootstrap
  - yarn global add postcss-cli

script:
  - yarn run check
  - yarn browserslist
  - NODE_ENV=production postcss tests/test.css --verbose
  - yarn lint
  - yarn test

before_deploy:
  - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
  - git remote set-url origin https://user:$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
  - git fetch origin $TRAVIS_BRANCH:$TRAVIS_BRANCH
  - git checkout $TRAVIS_BRANCH
  - yarn global add lerna-changelog
  - lerna-changelog

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn lerna publish --create-release github --yes
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: yarn lerna publish --canary --conventional-prerelease --force-publish --preid beta --pre-dist-tag beta --yes
    on:
      branch: develop

after_script:
  - yarn add -D @codechecks/client @codechecks/build-size-watcher @codechecks/type-coverage-watcher -W
  - yarn codechecks
