module.exports = {
  extends: ['@1stg'],
  rules: {
    '@typescript-eslint/member-ordering': 0,
    '@typescript-eslint/naming-convention': 0,
    '@typescript-eslint/no-explicit-any': 0,
    '@typescript-eslint/no-floating-promises': 0,
    '@typescript-eslint/no-magic-numbers': 0,
    '@typescript-eslint/no-type-alias': 0,
    '@typescript-eslint/no-unnecessary-condition': 0,
    '@typescript-eslint/no-unsafe-assignment': 0,
    '@typescript-eslint/no-unsafe-member-access': 0,
    '@typescript-eslint/no-unsafe-return': 0,
    '@typescript-eslint/restrict-plus-operands': 0,
    '@typescript-eslint/unbound-method': 0,
    'no-magic-numbers': 0,
    'promise/always-return': 0,
    'promise/catch-or-return': 0,
    'unicorn/explicit-length-check': 0,
    'unicorn/prefer-number-properties': 0,
  },
}
