name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }}
    strategy:
      matrix:
        node:
          - 14
          - 16
          - 18
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Check, Lint and test
        run: |
          pnpm check
          pnpm browserslist
          pnpm lint
          pnpm test
        env:
          EFF_NO_LINK_RULES: true
          PARSER_NO_WATCH: true

      - name: Check Postcss
        run: |
          pnpm add -Dw postcss-cli
          pnpm postcss tests/test.css --verbose
        env:
          NODE_ENV: production

      - name: Codecov
        uses: codecov/codecov-action@v3
