name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }}
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 22
          - 24
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --immutable

      - name: Check, Lint and test
        run: |
          yarn check
          npx browserslist
          yarn lint
          yarn test
        env:
          # https://github.com/ota-meshi/eslint-plugin-node-dependencies/issues/191
          ESLINT_NODE_DEPS: false
          PARSER_NO_WATCH: true

      - name: Check Postcss
        run: npx postcss-cli postcss tests/test.css --verbose
        env:
          NODE_ENV: production

      - name: Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run codacy-coverage-reporter
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        continue-on-error: true
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
